name: Deploy view-char

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      working-directory: ./
    
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - uses: actions/cache@v2
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: install
        working-directory: ${{ env.working-directory }}
        run: yarn --frozen-lockfile
      - name: Build
        working-directory: ${{ env.working-directory }}
        run: yarn build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_VIEW_CHAR }}'
          channelId: live
          projectId: view-char